name: Build workflows
on:
  workflow_dispatch:
jobs:
  windows-build:
    runs-on: macos-10.15
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: kivy20
          python-version: 3.9
          channels: conda-forge
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: create env
        shell: bash -l {0}
        run: conda install -y kivy=2.0 pyinstaller=4.10 requests
      - name: pip installs
        shell: bash -l {0}
        run: pip install pyo pyperclip
      - name: install smile
        shell: bash -l {0}
        run: pip install -e smile
      - name: create files
        shell: bash -l {0}
        run: echo $SI > serverinfo.txt && echo $ULCRT > cert.pem
      - name: package cogmood
        shell: bash -l {0}
        run: cd package && python -m PyInstaller cogmood_mackivy20.spec
      - name: save exe
        uses: actions/upload-artifact@v3
        with:
          name: mac package
          path: package/dist/test
